name: Docker Image CI

on:
  push:
    branches: [master, ci]
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "okcu" --password-stdin
        docker image build -t okcu/bebra:latest .
        docker push okcu/bebra:latest
